# Generated by Django 4.1.7 on 2023-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_img_url', models.CharField(max_length=200)),
                ('player_description', models.CharField(max_length=400)),
                ('player_status', models.CharField(max_length=200)),
            ],
        ),
    ]
